---
version: "3.1"

services:
  server:
    build: .
    security_opt:
      - label=disable
    volumes:
      - ./shared/consul.key:/shared/consul.key:ro
      - ./shared/nomad.key:/shared/nomad.key:ro
    ports:
      - "4646:4646"
      - "8080:8080"
      - "8081:8081"

  client:
    deploy:
      replicas: 3
    build: .
    security_opt:
      - label=disable
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./shared/consul.key:/shared/consul.key:ro
    depends_on:
      - server
