---
version: "3.1"

services:
  server:
    build: .
    security_opt:
      - label=disable
    volumes:
      - ./shared/:/shared/
    ports:
      - "4646:4646"

  client:
    deploy:
      replicas: 3
    build: .
    security_opt:
      - label=disable
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - ./shared/:/shared/
    depends_on:
      - server
